openage:
  #build: .
  image: yongjhih/openage
  #command: bash
  #command: bash -c "make build tests && make checkall"
  environment:
      - DISPLAY
  devices:
      #- "/dev/snd:/dev/snd"
      - /dev/snd
  volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app/age2dir
      - /app/openage/assets
